// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_cg.proto

package com.gyyx.dragon.ntxs_proto;

public final class p_cg {
  private p_cg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface p_cg_registerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gyyx.dragon.ntxs_proto.p_cg_register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string innerIp = 1;</code>
     */
    boolean hasInnerIp();
    /**
     * <code>optional string innerIp = 1;</code>
     */
    java.lang.String getInnerIp();
    /**
     * <code>optional string innerIp = 1;</code>
     */
    com.google.protobuf.ByteString
        getInnerIpBytes();

    /**
     * <code>optional int32 innerPort = 2;</code>
     */
    boolean hasInnerPort();
    /**
     * <code>optional int32 innerPort = 2;</code>
     */
    int getInnerPort();
  }
  /**
   * Protobuf type {@code com.gyyx.dragon.ntxs_proto.p_cg_register}
   */
  public static final class p_cg_register extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.gyyx.dragon.ntxs_proto.p_cg_register)
      p_cg_registerOrBuilder {
    // Use p_cg_register.newBuilder() to construct.
    private p_cg_register(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private p_cg_register(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final p_cg_register defaultInstance;
    public static p_cg_register getDefaultInstance() {
      return defaultInstance;
    }

    public p_cg_register getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private p_cg_register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              innerIp_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              innerPort_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gyyx.dragon.ntxs_proto.p_cg.internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gyyx.dragon.ntxs_proto.p_cg.internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register.class, com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register.Builder.class);
    }

    public static com.google.protobuf.Parser<p_cg_register> PARSER =
        new com.google.protobuf.AbstractParser<p_cg_register>() {
      public p_cg_register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_cg_register(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<p_cg_register> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INNERIP_FIELD_NUMBER = 1;
    private java.lang.Object innerIp_;
    /**
     * <code>optional string innerIp = 1;</code>
     */
    public boolean hasInnerIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string innerIp = 1;</code>
     */
    public java.lang.String getInnerIp() {
      java.lang.Object ref = innerIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          innerIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string innerIp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInnerIpBytes() {
      java.lang.Object ref = innerIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        innerIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INNERPORT_FIELD_NUMBER = 2;
    private int innerPort_;
    /**
     * <code>optional int32 innerPort = 2;</code>
     */
    public boolean hasInnerPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 innerPort = 2;</code>
     */
    public int getInnerPort() {
      return innerPort_;
    }

    private void initFields() {
      innerIp_ = "";
      innerPort_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getInnerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, innerPort_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getInnerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, innerPort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gyyx.dragon.ntxs_proto.p_cg_register}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gyyx.dragon.ntxs_proto.p_cg_register)
        com.gyyx.dragon.ntxs_proto.p_cg.p_cg_registerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gyyx.dragon.ntxs_proto.p_cg.internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gyyx.dragon.ntxs_proto.p_cg.internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register.class, com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register.Builder.class);
      }

      // Construct using com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        innerIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        innerPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gyyx.dragon.ntxs_proto.p_cg.internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_descriptor;
      }

      public com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register getDefaultInstanceForType() {
        return com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register.getDefaultInstance();
      }

      public com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register build() {
        com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register buildPartial() {
        com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register result = new com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.innerIp_ = innerIp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.innerPort_ = innerPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register) {
          return mergeFrom((com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register other) {
        if (other == com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register.getDefaultInstance()) return this;
        if (other.hasInnerIp()) {
          bitField0_ |= 0x00000001;
          innerIp_ = other.innerIp_;
          onChanged();
        }
        if (other.hasInnerPort()) {
          setInnerPort(other.getInnerPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gyyx.dragon.ntxs_proto.p_cg.p_cg_register) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object innerIp_ = "";
      /**
       * <code>optional string innerIp = 1;</code>
       */
      public boolean hasInnerIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string innerIp = 1;</code>
       */
      public java.lang.String getInnerIp() {
        java.lang.Object ref = innerIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            innerIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string innerIp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInnerIpBytes() {
        java.lang.Object ref = innerIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          innerIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string innerIp = 1;</code>
       */
      public Builder setInnerIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        innerIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string innerIp = 1;</code>
       */
      public Builder clearInnerIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        innerIp_ = getDefaultInstance().getInnerIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string innerIp = 1;</code>
       */
      public Builder setInnerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        innerIp_ = value;
        onChanged();
        return this;
      }

      private int innerPort_ ;
      /**
       * <code>optional int32 innerPort = 2;</code>
       */
      public boolean hasInnerPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 innerPort = 2;</code>
       */
      public int getInnerPort() {
        return innerPort_;
      }
      /**
       * <code>optional int32 innerPort = 2;</code>
       */
      public Builder setInnerPort(int value) {
        bitField0_ |= 0x00000002;
        innerPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 innerPort = 2;</code>
       */
      public Builder clearInnerPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        innerPort_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gyyx.dragon.ntxs_proto.p_cg_register)
    }

    static {
      defaultInstance = new p_cg_register(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gyyx.dragon.ntxs_proto.p_cg_register)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\np_cg.proto\022\032com.gyyx.dragon.ntxs_proto" +
      "\"3\n\rp_cg_register\022\017\n\007innerIp\030\001 \001(\t\022\021\n\tin" +
      "nerPort\030\002 \001(\005B$\n\032com.gyyx.dragon.ntxs_pr" +
      "otoB\004p_cgH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_gyyx_dragon_ntxs_proto_p_cg_register_descriptor,
        new java.lang.String[] { "InnerIp", "InnerPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
