server:
  port: 0
spring:
  application:
    name: playerstate
  cloud:
    loadbalancer:
      retry:
        enabled: true
hystrix:
  command: 
    default: 
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000  
playerstate:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 10
    MaxAutoRetries: 1
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.251.90:20000/eureka/,http://192.168.251.91:20000/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.int}